# Generated by Django 3.0.11 on 2021-09-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chat id'),
        ),
    ]
