# Generated by Django 3.0.11 on 2021-09-12 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipabusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipabusers',
            name='ip',
            field=models.CharField(max_length=255, validators=[django.core.validators.validate_ipv46_address], verbose_name='Ip address'),
        ),
    ]
